name: sveglio
favicon: null
layout_spectrum: 0.9435104322619736
typography_spectrum: 0.4434676233213395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#07060b'
    - '#b35c5d'
    - '#97b7a3'
    - '#3f7b72'
  brandStrength: 0.6875
  lightness: 0.125
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
