name: sveglio
favicon: null
layout_spectrum: 0.9435104322619736
typography_spectrum: 0.4434676233213395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.954919159412384
  lightness: 0.15431467280723155
  saturation: 0.5104959490709007
  rhythmicContrast: 0.04712727782316506
purpose: []
